### ISSUE TITLE
[TACKLE-107]Review - display only components that originate from the Assessment entity.

### ISSUE THREAD

**Issue by PhilipCattanach** [konveyor/tackle-ui#106]
Doughnut chart of risks, consolidated comments and the Assessment table (questions/answers/risks).

**Comment by PhilipCattanach** [comment]
@carlosthe19916 - Am I right in thinking that this issue is resolved by  https://github.com/konveyor/tackle-ui/pull/140?

**Comment by carlosthe19916** [comment]
@PhilipCattanach Yes, https://github.com/konveyor/tackle-ui/pull/140 contains already "Doughnut chart of risks, consolidated comments and the Assessment table"
