### ISSUE TITLE
[TACKLE-5] Notification alerts cannot be dismissed

### ISSUE THREAD

**Issue by nitishSr** [konveyor/tackle-ui#132]
On successfully creating new stakeholder, an alert with success message appears. 
It disappears after few seconds, but there should be an alert dismiss button, as it blocks user for that time frame to log out.
The username drop-down on top right is hidden and is not clickable for the duration of alert.
![ui_issue_notification](https://user-images.githubusercontent.com/43022982/116357175-d3715200-a819-11eb-845a-220a89999102.png)

**Comment by PhilipCattanach** [comment]
Add cross button on notification toastr message

**Comment by nitishSr** [comment]
This has been resolved now.
![notification_cancel](https://user-images.githubusercontent.com/43022982/123038529-32180e00-d40e-11eb-8164-2fe4ecef216f.png)
