### ISSUE TITLE
[TACKLE-5] Group(s) cannot be unassigned for stakeholder

### ISSUE THREAD

**Issue by nitishSr** [konveyor/tackle-ui#135]
User cannot remove any of the groups(s) from stakeholder edit option.

1. Go to controls -> Stakeholders tab
2. Edit any existing stakeholder
3. Remove the group/groups listed by clicking on cross icon
4. Save the edited stakeholder
5. Observe the group(s)
6. The group(s) for the stakeholder are not removed, even after editing and saving
![ui_user_groups_view](https://user-images.githubusercontent.com/43022982/116383677-b4cc8480-a834-11eb-8797-e2f422e3a38e.png)
![ui_issue_update_screen](https://user-images.githubusercontent.com/43022982/116383712-bc8c2900-a834-11eb-9308-737842b15eba.png)
![ui_issue_save](https://user-images.githubusercontent.com/43022982/116383729-c0b84680-a834-11eb-92e0-64829cb6f0c2.png)

**Comment by carlosthe19916** [comment]
This is something to be fixed in tackle-controls. There is already an issue https://github.com/konveyor/tackle-controls/issues/66 and once it is solved we can proceed to verify the UI works properly

**Comment by PhilipCattanach** [comment]
@nitishSr - This issue has been fixed under JIRA TACKLE-165
