### ISSUE TITLE
Pagination showing no data after deletion

### ISSUE THREAD

**Issue by mrizzi** [konveyor/tackle-ui#30]
**Steps to reproduce**

- insert 11 elements (e.g. 11 stakeholders)
- select pagination to show 10 elements per page
- go to the 2nd page with just one element
- delete that element
- the page says `No <elements> available` and `Create a new <element> to start seeing data here.` (ref. screenshot)
![Screenshot from 2021-03-18 12-59-20](https://user-images.githubusercontent.com/7288588/111756472-86a16f80-889a-11eb-967c-496a96094191.png)

**Expected behavior**
Reset pagination to page `0` if page, after deletion, is empty.

**Comment by carlosthe19916** [comment]
Closing this issue since https://github.com/konveyor/tackle-ui/pull/173 solved the bug
