### ISSUE TITLE
[TACKLE-5] Stakeholder: add new job function

### ISSUE THREAD

**Issue by mrizzi** [konveyor/tackle-ui#31]
When creating or editing a stakeholder entity, the user must be able to add a new job function using the dropdown menu.

**Comment by carlosthe19916** [comment]
Closing this issue because this has been implemented already. Adding a screenshot of the current Stakeholder modal:
![Screenshot from 2021-05-06 17-03-50](https://user-images.githubusercontent.com/2582866/117321120-263bb100-ae8d-11eb-884b-fea46b25da6a.png)
