### ISSUE TITLE
Error with starting docker-compose

### ISSUE THREAD

**Issue by dipjyotighosh** [konveyor/tackle-ui#343]
Hi,

I am getting the following errors while starting up using docker-compose. 

ERROR: for application-inventory  Container "56e8fa1d316a" is unhealthy.
ERROR: for pathfinder  Container "56e8fa1d316a" is unhealthy.
ERROR: for controls  Container "56e8fa1d316a" is unhealthy.
ERROR: Encountered errors while bringing up the project.

I also see this upon 'yarn start'

0h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'start'

Regards,
Dipjyoti Ghosh

**Comment by carlosthe19916** [comment]
@dipjyotighosh This repository belongs to Tackle V1 which won't have more releases. Please explore https://github.com/konveyor/tackle2-ui/ which is the current Tackle V2, currently, maintained version of Tackle.

**Comment by dipjyotighosh** [comment]
Ok thanks for the information, will do.
