### ISSUE TITLE
[TACKLE-8] Missing label when no application available

### ISSUE THREAD

**Issue by mrizzi** [konveyor/tackle-ui#39]
`terms.applications` appeared

![NoTerms](https://user-images.githubusercontent.com/7288588/111804193-23cacb00-88d0-11eb-9572-66e030a3bec5.png)

We must have in place some sort of automation to check all the label for the default language required have been defined because manual checks for labels would be error prone.

**Comment by carlosthe19916** [comment]
Closing this issue since it has been solved already and the main branch now contains the correct text.
