### ISSUE TITLE
Plus sign is not clickable on application inventory page

### ISSUE THREAD

**Issue by sshveta** [konveyor/tackle-ui#65]
From usability point of view when no application inventory is present , 
The first page shows "+ " sign  which is not clickable .

Also the text needs to be changed I think . It says  " No terms.applications available, Create a new terms.application to start seeing data here"

![Screenshot from 2021-03-24 15-29-23](https://user-images.githubusercontent.com/3866976/112392037-0d4cb700-8cb6-11eb-97cc-40d83f86bacf.png)

**Comment by mrizzi** [comment]
@sshveta good point about the :heavy_plus_sign: sign.
We can ask to the UX team what they think about associating an action with that sign because in the mockups it was not an action they required.

About the `terms.applications` it has been already reported in #39
